import pygame

#RENDERING
WIDTH = 1280
HEIGHT = 720
FPS = 60

#WORLD
WORLD_WIDTH = 6000
WORLD_HEIGHT = 6000
BACKGROUND_COLOR = (20,20,20)

#SIMULATION TIMING
SAVE_INTERVAL_MS = 60000    #Auto-save every 60 seconds real time
FAST_FORWARD_SPEED = 20    #Speed multipler

#FOOD
FOOD_COUNT = 350
FOOD_RESPAWN_INTERVAL = 20
FOOD_ENERGY_VAL = 50
FOOD_RADIUS = 4
FOOD_COLOR = (220,200,80)

#ORGANISM ENERGY
MAX_ENERGY = 100
BASE_ENERGY_DECAY = 0.1
VISION_ENERGY_COST = 0.0005
RADIUS_ENERGY_COST = 0.001
MOVEMENT_ENERGY_COST = 0.01

#ANTI IDLE PENALTIES
IDLE_VELOCITY_TRESHOLD = 0.2
IDLE_ENERGY_TAX = 0.05

#FITNESS WEIGHTS
FITNESS_FOOD_WEIGHT = 10
FITNESS_AGE_CAP = 500
FITNESS_AGE_DIVISOR = 100
FITNESS_DISTANCE_WEIGHT = 0.02

#Ornstein-Uhlenbeck NOISE
NOISE_MU = 0.0
NOISE_THETA = 0.5
NOISE_SIGMA = 0.8

#ORGANISM VISUAL AND INTERACTION
ORGANISM_COLOR = (100,220,100)
SELECTION_CLICK_PADDING = 5



#KEYBINDS
KEY_PAUSE_SELECTION = pygame.K_ESCAPE  #Clear selected organism & target
KEY_FOLLOW_ORGANISM = pygame.K_f       #Lock camera onto selected organism
KEY_FAST_FORWARD    = pygame.K_SPACE   #Hold to speed up simulation
KEY_NEXT_GENERATION = pygame.K_RETURN  #Skip wait screen on generation end
