import pygame
import math

# Display & World
WIDTH = 1280
HEIGHT = 720
FPS = 144

WORLD_WIDTH = 1500
WORLD_HEIGHT = 1500

SPATIAL_CELL_SIZE = 50

BACKGROUND_COLOR = (20, 20, 20)

DEFAULT_ZOOM = 1
ZOOM_FACTOR = 1.1
MIN_ZOOM = 0.01
MAX_ZOOM = 100

# Simulation & Timing
FAST_FORWARD_SPEED = 20
DEFAULT_SIMULATION_SPEED = 1

GENERATION_END_WAIT_TIME = 5  # Set to 0 for auto advance

PREY_POPULATION_SIZE = 80
PREDATOR_POPULATION_SIZE = 20
PARENT_COUNT = 10

# Bush
BUSH_COUNT = 20

# Food
FOOD_COUNT = 150
FOOD_RESPAWN_INTERVAL = 1
FOOD_ENERGY_VAL = 50
FOOD_RADIUS = 4
FOOD_COLOR = (220, 200, 80)

# Organisms
ORGANISM_COLOR = (100, 220, 100)
SELECTION_CLICK_PADDING = 5

MAX_ENERGY = 100
BASE_ENERGY_DECAY = 0.1
VISION_ENERGY_COST = 0.0005
RADIUS_ENERGY_COST = 0.001
REPRODUCTION_ENERGY_COST = 40
REPRODUCTION_CHILD_ENERGY = 50

REPRODUCTION_AGE = 200
REPRODUCTION_INTERVAL = 100
REPRODUCTION_OFFSET = 20

MAX_PREY = 160
MAX_PREDATORS = 40

ELITE_CLONE_CHANCE = 0.1

WALK_RUN_TRANSITION = 10

WALK_SPEED_COEFFICIENT = 0.003
RUN_SPEED_COEFFICIENT = 0.006

IDLE_VELOCITY_TRESHOLD = 0.2
IDLE_ENERGY_TAX = 0.05

FITNESS_FOOD_WEIGHT = 10
FITNESS_AGE_CAP = 1000
FITNESS_AGE_DIVISOR = 100

NOISE_MU = 0.0
NOISE_THETA = 0.5
NOISE_SIGMA = 1

# Genome & Mutation
MIN_SPEED = 50
MAX_SPEED = 150

MIN_VISION = 80
MAX_VISION = 300

MIN_RADIUS = 10
MAX_RADIUS = 15

MIN_TURN_SPEED = 0.5
MAX_TURN_SPEED = 2

NUM_RAYS = 10
RAY_FOV = math.radians(200)
RAY_CATEGORIES = ["food", "obstacle", "prey", "predator"]
VALUES_PER_RAY = 1 + len(RAY_CATEGORIES)

MUTATE_SPEED_STEP = 0.1
MUTATE_VISION_STEP = 5
MUTATE_RADIUS_STEP = 0.5
MUTATE_TURN_SPEED_STEP = 0.05

# Neural Network
INPUTS = NUM_RAYS + 3
HIDDEN = 10
OUTPUTS = 2

WEIGHT = 5
BIAS = 5

# UI & Visuals
COLOR_BORDER = (100, 100, 100)
COLOR_TEXT_PRIMARY = (255, 255, 255)
COLOR_TEXT_SECONDARY = (200, 200, 200)
COLOR_LEADERBOARD_TITLE = (255, 255, 0)
COLOR_PROMPT = (0, 255, 0)
COLOR_OVERLAY = (0, 0, 0, 200)
COLOR_VISION_CIRCLE = (80, 120, 255)

BORDER_THICKNESS = 2

HUD_X_PERCENT = 0.01
HUD_Y_PERCENT = 0.01

HUD_RIGHT_X_PERCENT = 0.87
HUD_RIGHT_Y_PERCENT = 0.01

LEADERBOARD_X_PERCENT = 0.03
LEADERBOARD_Y_PERCENT = 0.20

HUD_LINE_SPACING = 25

LEADERBOARD_Y_STEP = 30

# Controls
KEY_PAUSE_SELECTION = pygame.K_ESCAPE  # Clear selected organism & target
KEY_FOLLOW_ORGANISM = pygame.K_f  # Lock camera onto selected organism
KEY_FAST_FORWARD = pygame.K_SPACE  # Hold to speed up simulation
KEY_NEXT_GENERATION = pygame.K_RETURN  # Skip wait screen on generation end
KEY_DEBUG = pygame.K_F3  # Opens debug information

# Persistence & Logging
SAVE_FILE_PATH = "save.json"
CSV_LOG_PATH = "experiment_log.csv"
SAVE_INTERVAL_MS = 60000  # Auto-save every 60 seconds real time

FLOAT_ROUND_PRECISION = 2
JSON_INDENT = 4

# Assets
BUSH_IMAGE = pygame.image.load("assets/bush.png")
ORGANISM_SPRITE = pygame.image.load("assets/organism.png")
ORB_FOOD_SPRITE = pygame.image.load("assets/orb_food.png")
FOOD_BUSH_RADIUS = 150
