import pygame

# Display & World
WIDTH = 1280
HEIGHT = 720
FPS = 60

WORLD_WIDTH = 6000
WORLD_HEIGHT = 6000
BACKGROUND_COLOR = (20, 20, 20)

DEFAULT_ZOOM = 1
ZOOM_FACTOR = 1.1
MIN_ZOOM = 0.1
MAX_ZOOM = 100

# Simulation & Timing
FAST_FORWARD_SPEED = 20
DEFAULT_SIMULATION_SPEED = 1

GENERATION_END_WAIT_TIME = 5.0 #Set to 0 for auto advance

POPULATION_SIZE = 100
PARENT_COUNT = 5

# Food
FOOD_COUNT = 350
FOOD_RESPAWN_INTERVAL = 20
FOOD_ENERGY_VAL = 50
FOOD_RADIUS = 4
FOOD_COLOR = (220, 200, 80)

# Organisms
ORGANISM_COLOR = (100, 220, 100)
SELECTION_CLICK_PADDING = 5

MAX_ENERGY = 100
BASE_ENERGY_DECAY = 0.1
VISION_ENERGY_COST = 0.0005
RADIUS_ENERGY_COST = 0.001
MOVEMENT_ENERGY_COST = 0.01

IDLE_VELOCITY_TRESHOLD = 0.2
IDLE_ENERGY_TAX = 0.05

FITNESS_FOOD_WEIGHT = 10
FITNESS_AGE_CAP = 500
FITNESS_AGE_DIVISOR = 100
FITNESS_DISTANCE_WEIGHT = 0.02

NOISE_MU = 0.0
NOISE_THETA = 0.5
NOISE_SIGMA = 0.8

# Genome & Mutation
MIN_SPEED = 0.1
MAX_SPEED = 10

MIN_VISION = 80
MAX_VISION = 500

MIN_RADIUS = 10
MAX_RADIUS = 15

MIN_TURN_SPEED = 0.01
MAX_TURN_SPEED = 2

MUTATE_SPEED_STEP = 0.1
MUTATE_VISION_STEP = 5
MUTATE_RADIUS_STEP = 0.5
MUTATE_TURN_SPEED_STEP = 0.05

# Neural Network
INPUTS = 7
HIDDEN = 5
OUTPUTS = 2

WEIGHT = 5
BIAS = 5

# UI & Visuals
COLOR_BORDER = (100, 100, 100)
COLOR_TEXT_PRIMARY = (255, 255, 255)
COLOR_TEXT_SECONDARY = (200, 200, 200)
COLOR_LEADERBOARD_TITLE = (255, 255, 0)
COLOR_PROMPT = (0, 255, 0)
COLOR_OVERLAY = (0, 0, 0, 200)
COLOR_VISION_CIRCLE = (80, 120, 255)

BORDER_THICKNESS = 2

HUD_X_OFFSET = 20
HUD_Y_OFFSET = 20
HUD_LINE_SPACING = 25

LEADERBOARD_Y_START = 160
LEADERBOARD_Y_STEP = 40

# Controls
KEY_PAUSE_SELECTION = pygame.K_ESCAPE  # Clear selected organism & target
KEY_FOLLOW_ORGANISM = pygame.K_f       # Lock camera onto selected organism
KEY_FAST_FORWARD    = pygame.K_SPACE   # Hold to speed up simulation
KEY_NEXT_GENERATION = pygame.K_RETURN  # Skip wait screen on generation end

# Persistence & Logging
SAVE_FILE_PATH = "save.json"
CSV_LOG_PATH = "experiment_log.csv"
SAVE_INTERVAL_MS = 60000    # Auto-save every 60 seconds real time

FLOAT_ROUND_PRECISION = 2
JSON_INDENT = 4